server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kural?serverTimezone=UTC
    password: 20040928lja
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
